name: Build Linux Binary

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # v3 -> v4 yaptık

    - name: Set up Python
      uses: actions/setup-python@v5 # v4 -> v5 yaptık
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        pip install customtkinter watchdog pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --collect-all customtkinter --name "VortexSort_Linux" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4 # Hatanın asıl sebebi burasıydı, v4 yaptık
      with:
        name: VortexSort-Linux-Binary
        path: dist/VortexSort_Linux
